version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wallet-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    networks:
      - wallet-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  zipkin:
    image: openzipkin/zipkin
    container_name: wallet-zipkin
    ports:
      - "9411:9411"
    networks:
      - wallet-network

  prometheus:
    image: prom/prometheus
    container_name: wallet-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - wallet-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: wallet-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - wallet-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: wallet-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: wallet-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://wallet-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - wallet-network

networks:
  wallet-network:
    name: wallet-network
    driver: bridge

volumes:
  postgres-data:
